### PR TITLE
Cleanup ephemeral groups in integration tests

### PR DESCRIPTION
**Pull request by pietern**
## Changes

These tests left groups around that had to be removed manually/separately.

## Tests

Manually ran changed integration tests.

### CODE REVIEW

**Review by mgyucht — APPROVED** [review]
LGTM! Is this a good use of the `defer` keyword in golang?

**Comment by pietern** [comment]
@mgyucht It could be if tests didn't use `panic` for control flow (i.e. `t.FailNow()` or `t.Skip()`).

Defer works if you return from a function under normal circumstances, not when unwinding a `panic`.

**Comment by pietern** [comment]
@mgyucht Turns out my understanding is wrong, defer should still work with `panic`.

See https://go.dev/blog/defer-panic-and-recover.

**Comment by pietern** [comment]
@mgyucht The difference is that `t.Cleanup` is called on test completion and `defer` when returning from a function. So if you have a bunch of helper functions to construct state that you want to keep around for the duration of a test, `t.Cleanup` will do the trick, where `defer` wouldn't.

**Review by nfx — APPROVED** [review]

**Pull request merged**
